static: static
mysql:
  master-dsn: sysbase:SttA35BBx5dbl1xB7NS7@tcp(172.20.58.88:3306)/sysbase?parseTime=True&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci
  sources-dsn: [
    "sysbase:SttA35BBx5dbl1xB7NS7@tcp(172.20.58.88:3306)/sysbase?parseTime=True&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci"
  ]
  replicas-dsn: [
    "sysbase:SttA35BBx5dbl1xB7NS7@tcp(172.20.58.88:3306)/sysbase?parseTime=True&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci",
    "sysbase:SttA35BBx5dbl1xB7NS7@tcp(172.20.58.88:3306)/sysbase?parseTime=True&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci",
  ]
  # 空闲连接池中连接的最大数量
  max-idle-conns: 10
  # 打开数据库连接的最大数量
  max-open-conns: 100
  # 连接可复用的最大时间
  conn-max-lifetime: 1h

install-k8s:
  source-dir: /data/installk8s